# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
   
    # Add additional build and test steps if needed.


  - job: SendEmailJob
    displayName: "Send Email"
    pool:
      name: Default
    steps:
    - task: PowerShell@2
      displayName: SendEmail
      inputs:
        filePath: 'C:\KhalidSir\EmailConfiguration.ps1'
        

- stage: Approval
  displayName: 'Approval Stage'
  jobs:
  - job: ManualApprovalJob
    displayName: "Manual Approval"
    pool:
      name: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 5
      inputs:
        notifyUsers: 'afiya.mulla@cloverinfotech.com'
        instructions: "Hi, please validate"
