# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          scriptInline: |
                $smtpServer = "email.cloverinfotech.com"    
                $smtpPort = 587            
                $smtpFrom = "afiya.mulla@cloverinfotech.com"
                $smtpTo = "mullaafiya@gmail.com"
                $messageSubject = "Please approve the deployment"
                $messageBody = "Please approve the deployment"
                
                $smtp = New-Object Net.Mail.SmtpClient($smtpServer)
                $smtp.Send($smtpFrom, $smtpTo, $messageSubject, $messageBody)

- stage: Approval
  displayName: 'Approval Stage'
  jobs:
  - job: manual_approval
    displayName: "Manual Approval"
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 5
      inputs:
       notifyUsers: 'afiya.mulla@cloverinfotech.com'
       instructions: "Hi, please validate"

    - task: ManualIntervention@8
      inputs:
        instructions: 'kindly approve'
        emailRecipients: 'afiya.mulla@cloverinfotech.com'