# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


##- task: SendEmail@1
#  inputs:
#    To: 'spkute1919@gmail.com'
 #   From: 'afiya.mulla@cloverinfotech.com'
  #  Subject: 'Build Success'
   # Body: 'Hurray build success'
    #BodyAsHtml: false
    #AddAttachment: false
   # SmtpServer: 'email.cloverinfotech.com'
   # SmtpUsername: 'afiya.mulla@cloverinfotech.com'
   # SmtpPassword: 'Zimbra@123'
   # UseSSL: false

- task: SendEmail@1
  displayName: 'Send Email Notification'
  inputs:
    To: 'your.email@example.com'
    From: 'afiya.mulla@cloverinfotech.com'
    Subject: 'Build Notification'
    Body: 'The build has been completed successfully.'
  