# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: NuGetToolInstaller@1

- stage: Approval
  displayName: 'Approval Stage'
  jobs:
  - job: ApprovalJob
    displayName: 'Approval Job'
    steps:
    - task: ManualIntervention@8
      inputs:
        instructions: 'Please review the build and approve or reject.'
        emailRecipients: 'afiya.mulla@cloverinfotech.com'

# Uncomment and modify the following steps as needed for your pipeline
# - task: PublishSymbols@2
#   inputs:
#     symbolsFolder: '$(Build.SourcesDirectory)\YourSymbolFolder'
#     searchPattern: '**\bin\$(BuildConfiguration)\**\*.pdb'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)\YourArtifactFolder'
#     Contents: '**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory
