# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    # Add additional build and test steps if needed.

- stage: Approval
  displayName: 'Approval Stage'
  jobs:
  - job: ManualApprovalJob
    displayName: "Manual Approval"
    pool:
      name: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 5
      inputs:
        notifyUsers: 'afiya.mulla@cloverinfotech.com'
        instructions: "Hi, please validate"

  - job: SendEmailJob
    displayName: "Send Email"
    pool:
      name: server
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $smtpServer = "email.cloverinfotech.com"
          $smtpPort = 587  # Replace with your actual SMTP port number
          $smtpFrom = "afiya.mulla@cloverinfotech.com"
          $smtpTo = "mullaafiya@gmail.com"
          $messageSubject = "Please approve the deployment"
          $messageBody = "Please approve the deployment"
          
          $mailParams = @{
              From       = $smtpFrom
              To         = $smtpTo
              Subject    = $messageSubject
              Body       = $messageBody
              SmtpServer = $smtpServer
              Port       = $smtpPort  # Specify the correct SMTP port number
          }

          Send-MailMessage @mailParams

    - task: ManualIntervention@8
      inputs:
        instructions: 'kindly approve'
        emailRecipients: 'afiya.mulla@cloverinfotech.com'
